### ISSUE TITLE
[feature] Hide branding watermark option

### ISSUE THREAD

**Issue by MattSturgeon** [ParticleCore/Particle#535]
Some youtube channels enable a small in-video branding watermark In the bottom right of a video. This can be distracting when watching and adds no unique functionality\*

\* It behaves exactly the same as the below-video youtuber icon (`.yt-user-photo .yt-thumb-square`): hover over it and a popup will appear

---

Thankfully it can easily be hidden using incredibly simple CSS, since it is the only element with the `iv-branding` class:

```css
.iv-branding {
    display: none!important;
}
```

Or JavaScript:

```js
document.querySelector('.iv-branding').style.display = 'none';
```

You could also have css along these lines and toggle a class on `document.body` or something for enabling/disabling

```css
body.particle--hide-iv-branding .iv-branding {
    display: none!important;
}
```

```js
document.body.classList.add('particle--hide-iv-branding');
```
